ALTER TABLE foods DROP COLUMN IF EXISTS i1;
ALTER TABLE foods DROP COLUMN IF EXISTS i2;
ALTER TABLE foods DROP COLUMN IF EXISTS i3;
ALTER TABLE foods DROP COLUMN IF EXISTS i4;
ALTER TABLE foods DROP COLUMN IF EXISTS i5;

DROP TABLE IF EXISTS ingredients;