CREATE TABLE ingredients (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  impact INTEGER
);

ALTER TABLE foods
  ADD COLUMN
    i1 INTEGER NOT NULL references ingredients(id);

ALTER TABLE foods
  ADD COLUMN
    i2 INTEGER NOT NULL references ingredients(id);

ALTER TABLE foods
  ADD COLUMN
    i3 INTEGER NOT NULL references ingredients(id);

ALTER TABLE foods
  ADD COLUMN
    i4 INTEGER NOT NULL references ingredients(id);

ALTER TABLE foods
  ADD COLUMN
    i5 INTEGER NOT NULL references ingredients(id);