CREATE TABLE ratings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  rating INTEGER NOT NULL,
  userId INTEGER NOT NULL references users(id),
  foodId INTEGER NOT NULL references foods(id) ON DELETE CASCADE,
  date_rated TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE foods
  ADD COLUMN
    rating INTEGER NOT NULL;

-- definitely bad syntax in WHERE clause that needs to go on line 11
-- want to select the sum of the ratings in "ratings", where the foodId in "ratings" is the same as foodId in "foods"
--  SELECT sum(rating) FROM ratings WHERE foods(foodId) = ratings(foodId)