-- DANIEL psql -d congress-test-dos -f /Users/danielors/Documents/thinkful/ei28/capstonethree/server/seeds/seed.bills-test.sql
BEGIN;

TRUNCATE "bills";

INSERT INTO "bills" (
  bill_id,
  bill_type,
  number,
  bill_uri,
  title,
  sponsor_id,
  sponsor_name,
  sponsor_state,
  sponsor_uri,
  gpo_pdf_uri,
  congressdotgov_url,
  govtrack_url,
  introduced_date,
  active,
  house_passage,
  senate_passage,
  enacted,
  vetoed,
  cosponsors,
  committees,
  committee_codes,
  subcommittee_codes,
  primary_subject,
  summary,
  summary_short,
  latest_major_action_date,
  latest_major_action
)
VALUES
  ('1',
  'bill',
  '2',
  'http://cow.com/bill/text',
  'cow people should live as equals',
  '2',
  'cow',
  'tejas',
  'http://cow.com/sponsor',
  'http://cowpdf.com',
  'http://cowcongress.com',
  'http://cow.com',
  '2',
  true,
  'yes',
  'yes',
  'yes',
  'no',
  2,
  'farm committee',
  '1',
  '1',
  'cow',
  'a cow bill',
  'a cow',
  '5 days ago',
  'referred'
	),
  ('1',
  'bill',
  '2',
  'http://cow.com/bill/text',
  'cow people should live as equals',
  '2',
  'cow',
  'tejas',
  'http://cow.com/sponsor',
  'http://cowpdf.com',
  'http://cowcongress.com',
  'http://cow.com',
  '2',
  true,
  'yes',
  'yes',
  'yes',
  'no',
  2,
  'farm committee',
  '1',
  '1',
  'cow',
  'a cow bill',
  'a cow',
  '5 days ago',
  'referred'
	),
  ('1',
  'bill',
  '2',
  'http://cow.com/bill/text',
  'cow people should live as equals',
  '2',
  'cow',
  'tejas',
  'http://cow.com/sponsor',
  'http://cowpdf.com',
  'http://cowcongress.com',
  'http://cow.com',
  '2',
  true,
  'yes',
  'yes',
  'yes',
  'no',
  2,
  'farm committee',
  '1',
  '1',
  'cow',
  'a cow bill',
  'a cow',
  '5 days ago',
  'referred'
	);

COMMIT;